package exceptions

class ExitCommandCall : Exception("была вызвана функция выхода из программы") {
}